---
- hosts: "{{ hosts }}"
  become: true
  become_user: root
  vars_files:
    - vars.yml
  tasks:

  - name: stop sensu-client service
    command: docker exec -d pdns pkill -f sensu-client
    become: true

  - name: Get hostname of remote server
    command: hostname
    register: server_name

  - name: Get IP of remote server
    command: hostname -i
    register: server_ip

  # - name: create sensu directory in host server
  #   file:
  #     path: "/tmp/sensu_temp"
  #     state: directory

  - name: 'edit config file'
    lineinfile: 
     dest: "{{ playbook_dir }}/setup_sensu_client/config.json"
     regexp: '{{ item.regexp }}'
     line: '{{ item.line }}'
    with_items: 
        - { regexp: '(?<![\w\d])vhost(?![\w\d])', line: '    "vhost": "{{ vhost }}",' }
        - { regexp: '(?<![\w\d])host(?![\w\d])', line: '    "host": "{{ sensu_server }}",' }
        - { regexp: 'user', line: '    "user": "{{ sensu_username }}",' }
        - { regexp: 'password', line: '    "password": "{{ sensu_password }}"' }
    delegate_to: localhost


  - name: 'edit client file'
    lineinfile: 
     dest: "{{ playbook_dir }}/setup_sensu_client/conf.d/client.json"
     regexp: '{{ item.regexp }}'
     line: '{{ item.line }}'
    with_items: 
        - { regexp: 'address', line: '        "address": "{{ server_ip.stdout }}",' }
        - { regexp: 'name', line: '        "name": "{{ server_name.stdout }}",' }
    delegate_to: localhost        

  - name: create temp sensu directory in tmp
    file:
      path: "/tmp/sensu"
      state: directory

  - name: copy config file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/config.json"
      dest: "/tmp/sensu/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy client file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/conf.d/client.json"
      dest: "/tmp/sensu/conf.d/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: Rabbitmq file to tmp folder
    copy:
      src: "{{ playbook_dir }}/setup_sensu_client/config.json"
      dest: "/tmp/sensu/conf.d/rabbitmq.json"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy  transport file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/conf.d/transport.json"
      dest: "/tmp/sensu/conf.d/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy key.pem file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/ssl/key.pem"
      dest: "/tmp/sensu/ssl/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy cert.pem file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/ssl/cert.pem"
      dest: "/tmp/sensu/ssl/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy all config files to docker container
    command: docker cp /tmp/sensu/. pdns:/etc/sensu/
    become: true

  - name: start sensu-client service
    command: docker exec -dit pdns /opt/sensu/bin/sensu-client start
    become: true

