---
- hosts: servers
  become: true
  become_user: root
  vars_files:
    - vars.yml
  tasks:

  - name: stop sensu-client service on servers
    service:
      name: sensu-client
      state: stopped
    ignore_errors: yes

  - name: Get hostname of remote server
    command: hostname
    register: server_name

  # - debug:
  #    msg: "server name:  {{ server_name.stdout }}"

  - name: Get IP of remote server
    command: hostname -i
    register: server_ip

  # - debug:
  #    msg: "server IP :  {{ server_ip.stdout }}"



  - name: create sensu directory in host server
    file:
      path: "/tmp/sensu_temp"
      state: directory


  #  - name: Copy config files  (from localhost to 182server)
  #    synchronize: src={{ playbook_dir }} dest=/tmp/sensu_temp
  #    delegate_to: localhost

  - name: 'edit config file'
    lineinfile: 
     dest: "{{ playbook_dir }}/setup_sensu_client/config.json"
     regexp: '{{ item.regexp }}'
     line: '{{ item.line }}'
    with_items: 
        - { regexp: '(?<![\w\d])vhost(?![\w\d])', line: '    "vhost": "{{ vhost }}",' }
        - { regexp: '(?<![\w\d])host(?![\w\d])', line: '    "host": "{{ sensu_server }}",' }
        - { regexp: 'user', line: '    "user": "{{ sensu_username }}",' }
        - { regexp: 'password', line: '    "password": "{{ sensu_password }}"' }
    delegate_to: localhost


  - name: 'edit client file'
    lineinfile: 
     dest: "{{ playbook_dir }}/setup_sensu_client/conf.d/client.json"
     regexp: '{{ item.regexp }}'
     line: '{{ item.line }}'
    with_items: 
        - { regexp: 'address', line: '        "address": "{{ server_ip.stdout }}",' }
        - { regexp: 'name', line: '        "name": "{{ server_name.stdout }}",' }
    delegate_to: localhost        


  # - name: 'edit Rabbitmq file'
  #   lineinfile: 
  #    dest: "{{ playbook_dir }}/setup_sensu_client/conf.d/rabbitmq.json"
  #    regexp: '{{ item.regexp }}'
  #    line: '{{ item.line }}'
  #   with_items: 
  #       - { regexp: 'host', line: '    "host": "{{ sensu_server }}",' }
  #       - { regexp: 'user', line: '    "user": "{{ sensu_username }}",' }
  #       - { regexp: 'password', line: '    "password": "{{ sensu_password }}"' }


  - name: create temp sensu directory in tmp
    file:
      path: "/tmp/sensu"
      state: directory

  - name: copy config file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/config.json"
      dest: "/tmp/sensu/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy client file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/conf.d/client.json"
      dest: "/tmp/sensu/conf.d/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  # - name: copy rabbitmq file to tmp folder
  #   copy:
  #     src:  "{{ playbook_dir }}/setup_sensu_client/conf.d/rabbitmq.json"
  #     dest: "/tmp/sensu/conf.d/"
  #     owner: root
  #     group: root
  #     mode: "u=rw,g=r,o=r"

  - name: Rabbitmq file to tmp folder
    copy:
      src: "{{ playbook_dir }}/setup_sensu_client/config.json"
      dest: "/tmp/sensu/conf.d/rabbitmq.json"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"



  - name: copy  transport file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/conf.d/transport.json"
      dest: "/tmp/sensu/conf.d/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy key.pem file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/ssl/key.pem"
      dest: "/tmp/sensu/ssl/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copy cert.pem file to tmp folder
    copy:
      src:  "{{ playbook_dir }}/setup_sensu_client/ssl/cert.pem"
      dest: "/tmp/sensu/ssl/"
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"


  - name: copy all config files to docker container
    command: docker cp /tmp/sensu/. pdns:/etc/sensu/
    notify:
      - start sensu-client service
    become: true
  handlers:
    - name: start sensu-client service
      command: docker exec -d pdns /opt/sensu/bin/sensu-service start client
      become: true
